### ISSUE TITLE
Error on unit definition using square roots

### ISSUE THREAD

**Issue by ngollon** [sharkdp/numbat#561]
Using the unit definition
`unit test = sqrt(kg)`

the web interface breaks and always shows the error

```
[USER]: unreachable
RuntimeError: unreachable
    at https://numbat.dev/pkg/numbat_wasm_bg.wasm:wasm-function[655]:0xccfad
    at https://numbat.dev/pkg/numbat_wasm_bg.wasm:wasm-function[1471]:0x10f350
    at https://numbat.dev/pkg/numbat_wasm_bg.wasm:wasm-function[191]:0x84d30
    at https://numbat.dev/pkg/numbat_wasm_bg.wasm:wasm-function[108]:0x654cd
    at https://numbat.dev/pkg/numbat_wasm_bg.wasm:wasm-function[66]:0x4bc26
    at https://numbat.dev/pkg/numbat_wasm_bg.wasm:wasm-function[54]:0x3f8fc
    at https://numbat.dev/pkg/numbat_wasm_bg.wasm:wasm-function[843]:0xdd040
    at Numbat.interpret (https://numbat.dev/pkg/numbat_wasm.js:257:26)
    at ce.fn.init.interpret (https://numbat.dev/index.js:68:29)
    at s (https://numbat.dev/jquery.terminal.min.js:46:123939)
```

Link: https://numbat.dev/?q=unit+test+%3D+sqrt%28kg%29⏎test

**Comment by Goju-Ryu** [comment]
I just tried the same thing with `unit example = sqrt(m)` and got an error about recursion in rust. 
See example [here](https://numbat.dev/?q=unit+test+%253D+sqrt%2528kg%2529%E2%8F%8E)

**Comment by sharkdp** [comment]
Thank you very much for reporting this. Running this in debug mode on the command line shows a failing debug-assertion:

```
>>> unit test = sqrt(kg)

  unit test: Mass^(1/2) = sqrt(kilogram)

>>> test
thread 'main' panicked at numbat/src/unit.rs:140:21:
assertion failed: key[0].1.is_integer()
```

**Comment by sharkdp** [comment]
This is now fixed.
